spring.application.name=loja
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./dados/loja;AUTO_SERVER=TRUE

spring.sql.init.mode=always

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
