spring.application.name=loja
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./dados/loja

spring.sql.init.mode=always